a<-read.csv("summer.csv")
a$ev<-paste(a$Discipline, a$Event, a$Gender, sep="_")
b<-a[c("Year", "ev")]
c<-unique(b)
q<-table(c$Year)
plot(q, xlab="Year", ylab="Events", main="Number of Events at Summer Olympics", type="l")

qa<-as.data.frame(q[11:27])
names(qa)=c("Year", "Event")
qa$Year<-as.numeric(as.character(qa$Year))
plot(qa, xlab="Year", ylab="Events", main="Number of Events at Summer Olympics from 1950 onwards")
li_a<-lm(Event~Year, data=qa)
abline(li_a)
predict(li_a, list(Year=2040)) 

d<-read.csv("winter.csv")
d$ev<-paste(d$Discipline, d$Event, d$Gender, sep="_")
e<-d[c("Year", "ev")]
f<-unique(e)
r<-table(f$Year)
plot(r, xlab="Year", ylab="Events", main="Number of Events at Winter Olympics", type="l")

ra<-as.data.frame(r[14:22])
names(ra)=c("Year", "Event")
ra$Year<-as.numeric(as.character(ra$Year))
plot(ra, xlab="Year", ylab="Events", main="Number of Events at Winter Olympics from 1984 onwards")
li_b<-lm(Event~Year, data=ra)
abline(li_b)
predict(li_b, list(Year=2040))

cherry<-read.csv("cherry.csv")
washtemp<-read.csv("washtemp.csv", head=TRUE, sep='')
frame_cherry<-data.frame(cherry$Year, cherry$Yoshino.peak.bloom.date)
frame_washtemp<-data.frame(washtemp$YEAR, washtemp$MAR)
names(frame_cherry)[1:2]<-c("Year", "BloomDays")
names(frame_washtemp)[1:2]<-c("Year", "MarchTemp")
frameboth<-merge(frame_cherry, frame_washtemp, by = intersect(names(frame_cherry), names(frame_washtemp)), by.x='Year')
plot(frameboth$BloomDays, frameboth$MarchTemp, xlab="Bloom Days", ylab="March Temperature", main="Bloom Days by Temperature in Washington, DC")
abline(lm(frameboth$MarchTemp~frameboth$BloomDays), col="red")